### ISSUE TITLE
Dataframe's schema is None after assign dataframe.__class__ = Dataset

### ISSUE THREAD

**Issue by hmtrii** [kaiko-ai/typedspark#726]
My packages:
```
python 3.11
pyspark==4.0.1
typedspark==1.5.5
```
Code from the [tutorial](https://typedspark.readthedocs.io/en/latest/type_checking.html):
```
from pyspark.sql import SparkSession
import pandas as pd
from typedspark import Column, DataSet, Schema
from pyspark.sql.types import LongType, StringType

spark = SparkSession.Builder().config("spark.ui.showConsoleProgress", "false").getOrCreate()
spark.sparkContext.setLogLevel("ERROR")
class Person(Schema):
    id: Column[LongType]
    name: Column[StringType]
    age: Column[LongType]


df = spark.createDataFrame(
    pd.DataFrame(
        dict(
            id=[1, 2, 3],
            name=["John", "Jane", "Jack"],
            age=[20, 30, 40],
        )
    )
)
# no errors raised
df = DataSet[Person](df)
```
The error at line https://github.com/kaiko-ai/typedspark/blob/af9b66cad8e4c7d12df690f7609783ed5eb13bfe/typedspark/_core/validate_schema.py#L27
`AttributeError: 'NoneType' object has no attribute 'fields'`

Cause:
After this line: https://github.com/kaiko-ai/typedspark/blob/af9b66cad8e4c7d12df690f7609783ed5eb13bfe/typedspark/_core/dataset.py#L188

The method: `dataframe.schema` is None

I tested with the PySpark version **3.5.2**, and it **succeeded**

**Comment by nanne-aben** [comment]
Uff, yes, typedspark doesn't work with Spark >=4.0.0... I think we urgently need to fix this.

I'll have a go at it, but also curious: would you be willing to contribute here?

**Comment by nanne-aben** [comment]
Hi @hmtrii 

This should now be fixed in the latest version of typedspark (1.6.0), following #768. Let me know if it still doesn't work!
